### ISSUE TITLE
What MARVL files to use

### ISSUE THREAD

**Issue by snailrowen1337** [zengyan-97/CCLM#1]
Thanks for open-sourcing this, I'd love to try the model out!

For testing I wanted to start with the the marvl/nlvr2 evaluation. From [run.py](https://github.com/zengyan-97/CCLM/blob/master/run.py#L112) it seems like I need to obtain a file called `marvl_official.tar`. However, the MARVL files seems to be distributed [here](https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/42VZ4P) in the form of zip-files. 

Where should I obtain `marvl_official.tar`? Thanks!

**Comment by memory4963** [comment]
Hi, thank you for pointing out this, we have updated our code and `Requirements` in README, please kindly check it.

**Comment by snailrowen1337** [comment]
Thanks, this seems to solve the marvl issue! However, the script now crashes with 

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/finetune/nlvr_en/nlvr_train.json'
```

Should I use [this file](https://github.com/lil-lab/nlvr/blob/master/nlvr2/data/train.json) and rename it to `nlvr_train.json`? And for the nlvr images, is there an example for how the folders should be renamed/structured? Sorry for the many questions, and thanks!!

**Comment by zengyan-97** [comment]
Hi, 
You can download json files for fine-tuning on English tasks from this repo: https://github.com/zengyan-97/X-VLM. 
https://drive.google.com/file/d/1XFz1Vtz7MCBLn4_1QEojhFJ5Iw3eH3X4/view?usp=sharing
`nlvr_train.json` is included in this `finetune.tar`.

**Comment by snailrowen1337** [comment]
downloading the `finetune.tar` file works, thanks!!
