### ISSUE TITLE
Problem when run the pretrain code

### ISSUE THREAD

**Issue by BUAADreamer** [zengyan-97/CCLM#10]
When I run the pretrain command  `python3 run.py --task "pretrain_cclm_3m" --dist "1" --output_dir "output/"` I got problem as follow
`can't open file 'Pretrain_multilingual.py': [Errno 2] No such file or directory`
It seems like repo lacks a file called Pretrain_multilingual.py, or I misunderstand something? L85 in the run.py has this file name

**Comment by JeffTianZy** [comment]
Here. [#2 ](https://github.com/zengyan-97/CCLM/issues/2#issuecomment-1191155825)

**Comment by BUAADreamer** [comment]
> Here. [#2 ](https://github.com/zengyan-97/CCLM/issues/2#issuecomment-1191155825)

Thank you!
