### ISSUE TITLE
mscoco 1k test 

### ISSUE THREAD

**Issue by BUAADreamer** [zengyan-97/CCLM#17]
Can you give your mscoco en en.1k_test.json? Because in some other research, I find that they use the mean of 5 folder test of 5k image-text. I have no idea about how to get this 1k test

**Comment by zengyan-97** [comment]
Hi,

Sorry for my late rely.

It is an open-sourced test set. Please search "mscoco 1k test set". 
I guess I found this file from github repo of UNITER or OSCAR or VinVL.

**Comment by zengyan-97** [comment]
There is a test set named "mscoco 1k test set". 
So, I got this test set from a well-known work, maybe oscar or vinvl.
