### ISSUE TITLE
Folder structure for pretraining?

### ISSUE THREAD

**Issue by snailrowen1337** [zengyan-97/CCLM#2]
I'd want to try pretraining CCLM, but am having issues putting the data in the correct format. I was wondering, are details regarding how to structure the pretraining data/folders available anywhere? The README says `please read the code dataset/pretrain_dataset.py`, but this file does not exists. Thanks for sharing your work!

**Comment by snailrowen1337** [comment]
This line https://github.com/zengyan-97/CCLM/blob/master/run.py#L85 also refers to a file "Pretrain_multilingual.py" which I cannot find in the repo?

**Comment by JeffTianZy** [comment]
I recently ran pretraining task on CCLM-3M settings. I think the README  [pretrain_dataset_multilingual.py](https://github.com/zengyan-97/CCLM/blob/master/dataset/pretrain_dataset_multilingual.py).
I processed the cc3m-uc2-mm-text-only (from Google Drive) into following format:
CCLM/
    cc3m/
        part-00000.data
            [
              {
                 "binary": "PATH TO IMAGE FILE",
                 "caption": [{"cs": "CAPTIONS", "de": "CAPTIONS", "fr": "CAPTIONS", … }]
              }, ...
            ]
        part-00001.data
        part-00002.data
        ...
and with some little changes in config, the pretraining task runs successfully.


> This line https://github.com/zengyan-97/CCLM/blob/master/run.py#L85 also refers to a file "Pretrain_multilingual.py" which I cannot find in the repo?

Pretrain.py

**Comment by zengyan-97** [comment]
Hi, 
sorry, I forgot to reply this one... 
A quick reply first. 
Pretrain_multilingual.py is Pretrain.py. I forgot to rename it in this released version...

I will check your other questions later.

**Comment by snailrowen1337** [comment]
Thanks, renaming to Pretrain.py seems to help! If you have any advice regarding the folder structure for pretraining I'd be very grateful :)
