### ISSUE TITLE
For model architecture

### ISSUE THREAD

**Issue by jongjyh** [zengyan-97/CCLM#4]
Hi,

Thank you for contributing a such great work! I found that the architecture is a little bit similar to Coca, is that because you were inspired by that or any other work? Can you provide some clues?

**Comment by zengyan-97** [comment]
Hi, 

Thanks for your interest. 

The multimodal parts of CCLM follows our previous work, X-VLM. 
X-VLM is for multi-grained vision language pre-training, which was released in Nov 2021. 
(https://github.com/zengyan-97/X-VLM)
