### ISSUE TITLE
Training data of CCLM-3M model

### ISSUE THREAD

**Issue by cv-learner** [zengyan-97/CCLM#5]
Hi, thank you for releasing code! This is really a great work.

Did the CCLM-3M checkpoint you released (https://github.com/zengyan-97/CCLM/blob/master/README.md#checkpoints) only use CC3M+wikimatrix for pre-training? I pre-train the model on CC3M+wikimatrix as you mentioned, however, the retrieval performance on xFlickrCO is much worse than the released checkpoint.

**Comment by cv-learner** [comment]
I train the model with Pretrian.py and configs/Pretrain_3m.yaml, then evaluate the model with xFlickrCO.py and cclm-base-ft/xFlickrCO.yaml (with some setting like image_res modified).

For simplicity, I only evaluate the result of dual encoders (https://github.com/zengyan-97/CCLM/blob/master/xFlickrCO.py#L108). The result of the released checkpoint is resonable (about 40% R@1), while the result of my pre-trained model is only about 20+% R@1.

Is there any proplem of my evaluation? Thanks a lot!

**Comment by zengyan-97** [comment]
Hi, 
sorry for my late reply... i missed this one...

CCLM_3m was indeed pre-trained using CC3M+wikimatrix only. 

I don't know why you obtain inferior performance... Did you use configs/Pretrain_3m.yaml and pretrain the model using 8 GPUs?
