### ISSUE TITLE
More supported languages?

### ISSUE THREAD

**Issue by zhongpeixiang** [zengyan-97/CCLM#9]
This is an excellent work!

The current checkpoint only supports the languages in IGLUE, which may limit its use cases. Do you have any plans to release a model that supports all the languages in XLM-R?

Thanks,
Peixiang

**Comment by zengyan-97** [comment]
Hi, 

Sorry for my late reply. 

It seems relatively low ROI for me to collect more multi-lingual text pairs to support more languages. 

Recently, I further pre-train CCLM based on X2-VLM(https://github.com/zengyan-97/X2-VLM) and substantially improve the performance. I guess this version of CCLM can also perform competitively on multi-modal tasks in other languages. 

I will release this CCLM this month or next month.
